### ISSUE TITLE
Deepslate titanium veins have no titanium

### ISSUE THREAD

**Issue by truepurpledino** [Kisuny/MI-Foundation#1]
Since minecraft\kubejs\data\geocluster\deposits\titanium.json calls for modern_industrialization:deepslate_titanium_ore, which doesn't exist, deepslate titanium ore veins have no titanium ore.
![image](https://github.com/user-attachments/assets/1a34a708-a7db-4b89-be04-1d893cf64707)

**Comment by Kisuny** [comment]
Will be fixed in 0.0.5 version.

Thank you!
