### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by Racounous** [Kisuny/MI-Foundation#5]
Hi, I'd like to start by saying how impressive all the custom content and mod integrations in this pack is. I'd love for it to be even better so i leave some suggestions of potential improvements. These are subjetive of course and i might be missing something but i'd love hear some feedback.

-Chunk loaders are a late-game item, but are quite required for mods like MI with processing lines that take a long time and power infrastructure that needs to be operational at all times. Xaero's map has a chunk loading feature that can be limited  for balance.
-There is no mass storage/transport prior to ME chest or skulker boxes, making moving large amounts of items tedious. Perhaps something like https://modrinth.com/mod/carry-on would be a solution
-Reinforced chests are very expensive (32 ingots) when compared to other alternatives (like probably chests). 
-A mod like https://modrinth.com/mod/toms-storage would reduce crafting tedium prior to ae2 although i understand the decision
/ to gate such powerful functionality
-[Just Enough Resources (JER)](https://modrinth.com/mod/just-enough-resources-jer) would be an interesting addition for locating ores, although i am unsure if it is compatible with the geolosys generation.
-Tool quality is annoying most of the time as there is a large chance of your costly, newly made tool having a crippling negative. A cheap way to remove modifiers or disabling modifiers on all crafted items would combat this. Additionally, reforge runes seems very rare for how random their effects are.
As a side effect, fishing rods, in particular, are crafted with -luck modifiers most of the time and fishing is not nearly as rewarding as the quest guide claims it is.
-Is there any kind of builder's wand/building aid available ?
-NBT editor is enabled if the world has cheats enabled and cannot be hidden or disabled, unlike REI cheat mode. Can this mod be disabled or is it required?

**Comment by truepurpledino** [comment]
I personally don't recommend adding Tom's. Coming from Statech Industries, Tom's has a bunch of issues including : duping items, voiding items, creating immense lag at large scale, creating lag when used with MI pipes. 
I also think the reinforced chests are too expensive to be worth doing over spamming Probably Chests.
I also think chunk loading it way to gated and expensive currently, and that it does not add any noticable difficulty but only restricts the player's ability to make larger bases as simulation distance is limited, and only makes it so players will tend to afk (which is bad) in the factory more if they can't explore while the automation does its work (when chunk loaded).
I also would love to have a dolly or Carry On to move chests.

**Comment by Racounous** [comment]
Thank for your feedback. I was not aware of those issues with tom's mod, in that case, i'd rather avoid it as well. However, a way to craft directly from storage (like the crafting station from tinkers) would be very handy. I have not found a good alternative so far.
-Chunk loading is usually very limited for that very reason but even a small amount for "free" chunk loading per player would be helpful
-I didn't even consider backpacks as they are gated behind midas gold but yes, it is an option.
-JER does add unnecessary information and, especially if it does not work with custom ore gen, wouldn't be a good addition.
-Ah, i see, the constructor's staff, it did not sound like what i was looking for from the tooltip.

**Comment by Kisuny** [comment]
1. In the future, we will change the chunkloader system by simplifying it
2. [Carryon added](https://github.com/Kisuny/MI-Foundation/commit/477e9e8fd3c66c0be997f84bed9e07b530382f70)
3. Creating chests has been [simplified](https://github.com/Kisuny/MI-Foundation/commit/39814b23180824e57d6fcc1cf953bb67ed5ca10a)
4. The toms storage mod has many problems and dupes, unfortunately we will not add it!
5. The JER mod will not be added, no need, you can try to add it yourself.
6. Initially insturments [now have no re-forging](https://github.com/Kisuny/MI-Foundation/commit/d7228d2b4fceb6d55ecebc6e92efb88736c3f650), you can add re-forging with a rune. Tools found in structures will appear with re-forging!
7. Fishing rods have many new resources added to the pool of possible items! Including magical ingots!
8. [Removed ](https://github.com/Kisuny/MI-Foundation/commit/4ca7229e89abe476a936d2e95ce118bcf49c3a89) NBT editor
